server:
  port: 80

spring:
  application:
    name: cloud-cumsumer-order

eureka:
  client:
    #false表示不向服务中心注册自己
    register-with-eureka: true
    #false表示自己就是服务中心，职责是维护服务，不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与eureka service交互的地址 查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/
