server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    #false表示不向服务中心注册自己
    register-with-eureka: false
    #false表示自己就是服务中心，职责是维护服务，不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka service交互的地址 查询服务和注册服务都需要依赖这个地址
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
