server:
  port: 8001

spring:
  application:
    name: cloud-payment-ourchem.springcloud.service
  datasource:
    url: jdbc:mysql://localhost:3307/springcloud-demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong;useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml
